title: "Headings"
status: "ready"

context:
  headings:
    -
      message: Lorem ipsum dolor sit amet consecteteur adipicising elit aram
      tag: h1
    -
      message: Lorem ipsum dolor sit amet consecteteur adipicising elit aram
      tag: h2
    -
      message: Lorem ipsum dolor sit amet consecteteur adipicising elit aram
      tag: h3
    -
      message: Lorem ipsum dolor sit amet consecteteur adipicising elit aram
      tag: h4
    -
      message: Lorem ipsum dolor sit amet consecteteur adipicising elit aram
      tag: h5
